version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8012:8012"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword

volumes:
  pgdata:
